### ISSUE TITLE
Add "Demo" section to the Crispness menu

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#256]
With menu items we that have briefly discussed before.

- Show record timer

Since you are already planning this, all we need is to find good position for the times on the screen. Presumably, it should be placed in the top-right corner, just like on mockup below.

- Timer position

Default should be top-right, but someone will be more happy with different placement? Placements could be: top-right, bottow-right, bottom-left, top-left, top-centered, low-centered.

- Timer color

Erm, it is cool to have, but probably it will be better to set timer's color by colored messages logic.

- Timer counting up when recording a demo and counting down when playing back

Maybe it's worth to make this item as "Show remaining playback time", disabled by default. Some people may be more familiar with counting up times and point out to the increasing, not decreasing time (i.e. to 12:34, not -12:34 in time). While recording timer always will be counting up by very obvious reason.

#### Non-related to the menu

Just to don't forget.

- Support for pressing `pause` while watching and pausing demo playback

Some description here.

- Switching between `playdemo` and `timedemo` mode on the fly

Since there are two values, one key will be enough to switch them. But what key it should be? Maybe `shift` or `caps lock` as a "logical speed modifier"? Or maybe arrow keys which are not invoking game menu while demo playback with following logic:

`up` set playback mode to the `timedemo`
`down` set playback mode to the `playdemo`
`left` set playback to reverse mode _(is it possible?)_
`right` set playback to normal mode

#### Mockup

Suggested place for the times is top-right corner. Following traditional Crispy colors, it should be colored white if colored texts are enabled and colored red if not. Or maybe it is worth to color it yellow/gold, since it's a slightly different thing, than standard HUD messages.

No need to always show HH, let them appear only if hour are > 0 while the record.
Not sure about real necessity of MS, better ask someone who is more familiar with demo recording / speedrunning.

Another idea is to add blinking `*`, but probably it's really not necessary.

![](http://screenshot.ru/upload/images/2018/01/19/demoa8257.png)

_Edit: Suggestion №81_

**Comment by fabiangreffrath** [comment]
> Show record timer

Yep, will come.

> Timer position
> Timer color

I think it will be grey font in the top-right corner, just as your mock-up shows. IMHO everything else would be symptoms of over-engineering and featuritis. ;)

BTW, I am also playing the thought of using the font from the ammo overview in the bottom right corner of the status bar, but this one doesn't have a colon (':'), right?

> Timer counting up when recording a demo and counting down when playing back

*sigh* Yes, this would be another item in the menu, probably along the lines "counter on demo playback: increasing/decreasing".

> No need to always show HH, let them appear only if hour are > 0 while the record.

Indeed.

> Not sure about real necessity of MS, better ask someone who is more familiar with demo recording / speedrunning.

I guess I will show "gametics % 35" behind seconds so that the timer switches to a new second as soon as the tics counter reacher 35.

> Another idea is to add blinking *, but probably it's really not necessary.

I think this would be rather distracting, to have a blinking "something" in the peripheral view while playing highly concentrated.

**Comment by JNechaevsky** [comment]
> BTW, I am also playing the thought of using the font from the ammo overview in the bottom right corner of the status bar, but this one doesn't have a colon (':'), right?

Sadly, yeah, there is no such symbol, there are only 0-9 numbers :( Possible approach it to hard-code ":" symbol into executable and use coloring for any possible non-standard small digits, or even hard-code whole array of digits to make them resource-independent, but barely this approach is acceptable.

Another idea for menu items:

- Make demo progress bar optional

Personally, I like it and find it useful, but AFAIR there was couple of request to make it optional, so maybe it is worth to add an option for disabling/enabling this bar.

**Comment by fabiangreffrath** [comment]
I am also considering the unique timer that CnDoom introduced, will ask @fx02 if it is okay to take and modify it.

**Comment by fabiangreffrath** [comment]
> Make demo progress bar optional

Yep, this would also have to get its place in the "Demos" menu.

**Comment by fx02** [comment]
You should ask Andrey Budko as we asked/took it from prboom+.

**Comment by fabiangreffrath** [comment]
Hm, strange. I cannot seem to find any related code in PrBoom+'s sources.

**Comment by fabiangreffrath** [comment]
Edit: found it!

**Comment by fabiangreffrath** [comment]
> You should ask Andrey Budko as we asked/took it from prboom+.

@fx02 So, how is the Copyright line supposed to look like if I imported your changes from CnDoom?

**Comment by fx02** [comment]
Dunno, vv took it, not sure if I still have communication with him, but I think he never got reply from Andrey.

**Comment by Zodomaniac** [comment]
Can this issue be closed now?

**Comment by fabiangreffrath** [comment]
I think so, although i haven't implemented *all* of the ideas from the initial posting. I'll leave it to @JNechaevsky to open a separate issue for them should they become pressing. ;)

**Comment by JNechaevsky** [comment]
Actually... I'm already wish to annoy with suggestions, or better say - recommendations about timer's appearance. Nope, it's not regarded to colon symbol, it's about pixel-perfect placement, color and so on.

Some time ago I have implemented local time widget and suffered a lot of self- _"no, this looks bad, and no, this placement is not perfect"_, so I believe my experience will be useful, at least for some additional discussion.

Just give me some time please, currently I'm all in Press Beta research/implementation.  :neckbeard:

**Comment by JNechaevsky** [comment]
Fabian, before I'll post a suggestion about timer -- am I right with thinking that you have rejected the idea of using gray color because of color translation? I.e., if timer will be colored gray, it's shadow will also remain gray and thus, digits will be blurred.

**Comment by fabiangreffrath** [comment]
I am not sure what you mean? The timer is colored to gray, it is just using the Ammo widget font instead of the HUD font.

**Comment by JNechaevsky** [comment]
Yep, I see that timer is using `CR_GRAY` and STYSNUM font which is initially yellow, but it seems to be colored white anyway:

![](http://screenshot.ru/upload/images/2018/02/06/white9a6c5.png)
RGB values for white (non-shadow) color is: (r: 252 / g: 252 / b: 252). And probably colors are white because of yellow color is too bright (r: 255 / g: 255 / b: 115), and color translation is very limited in 256 colors.

The thing I would like to suggest - make timer color slightly darken. At the moment it's too notably bright, especially when playing in full screen on 27" monitor with turned off lights. It does not look harmonious with dark Doom colors. Another thing is a placement, but that's a topic for separate issue.

So how do you think, maybe it's worth to try to write new translation table, especially for this timer? Or maybe it is worth to try `CR_DARK`?

**Comment by fabiangreffrath** [comment]
Unfortunately, it is currently impossible to combine both `CR_DARK` and `CR_GRAY` into something like `CR_DARKGRAY`, but we could create such a table from scratch (or, rather let `V_Colorize()` create one, that is). But this table would only serve this one purpose then, and I still don't think it's *that* bad as it is. :/

**Comment by JNechaevsky** [comment]
Fair enough, and your decision must be last. :) 

But probably making timer slightly transparent could help, but also probably not, because transparency in 256 colors is... Let's just say _"not perfect enough for all out needs"_.

As about placement - hmm. Well, since this demo timer is a special thing, maybe it will be better if it will stay where it is now. I was thinking about suggesting slightly different position, according to my implementation of ingame local timer. Take a look at this mockup, maybe you'll find some resonable logic:

![](http://screenshot.ru/upload/images/2018/02/06/timere6088.png)

But in my case digits are literally new font.

**Comment by fabiangreffrath** [comment]
> But probably making timer slightly transparent could help

Transparency could help, sure!
